### ISSUE TITLE
Nix Search API needs documentation

### ISSUE THREAD

**Issue by Narice** [NixOS/nixos-search#296]
Hi!

I would like to make an android companion app for NixOS and would like more info on the API.
I could just use what I got from the reverse-engineering I did by now but I thought it was most appropriate to contact the devs about the possible usage of this very useful API outside its current realm.
The main problem right now on my [art is the fact that there are no documentation on the API.

What I know right now:
API url: `https://nixos-search-5886075189.us-east-1.bonsaisearch.net:443`
Username: `z3ZFJ6y2mR`
password: `ds8CEvALPf9pui7XG` (this is shown in the `src/index.js` file in case it was not intentional)
`username:password` is encoded in Base64 thus giving: `ejNaRko2eTJtUjpkczhDRXZBTFBmOXB1aTdYRw==` for the authentication bearer token
The CORS policy seems to be `*` but I might be wrong on that.
And I know the overall shape of a request and of a response thanks to Firefox network console.

What I want to know is if there are resources I could use to make my life easier like a postman playground, documentation, some insight on the API, the gotchas of the API or anything you know on it really ^^

Thank you!

**Comment by turboMaCk** [comment]
afaik you don't need CORS unless your client runs in web browser anyway. The api is just Elastic search. All you need to know is schema of ES indexes and endpoint. https://www.elastic.co/elasticsearch/ Just be aware that there is no grantee that ES index won't change over time as needed to support the official web client.

**Comment by Narice** [comment]
woaw thanks for the quick response!
thank you so much, I'm not familiar with ES so I'll research it now then, thanks for the link :wink:

**Comment by Narice** [comment]
Sorry to bother again but I have some problems with getting kibana up and running for visualizing your ES's data etc.
I thought this was the optimal solution but maybe I misunderstood your comment above and there is a simpler solution, if this is the case, don't hesitate to interrupt me.
I'm using the username and password and host given above in a docker-compose file:
```yml
version: '3.8'

services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.2.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: https://z3ZFJ6y2mR:ds8CEvALPf9pui7XG@nixos-search-5886075189.us-east-1.bonsai.io
      ELASTICSEARCH_USERNAME: z3ZFJ6y2mR
      ELASTICSEARCH_PASSWORD: ds8CEvALPf9pui7XG
```
I made sure after some troubleshooting to use the same version as your ES server so that should be fine on this part.
What I get is an Authentication error. Are the credentials above too low level to setup a kibana targeting it?
If this is the case, is there another solution than using kibana?

On another note, I would like to make sure I understood correctly your message.
the schema of ES indexes is the json request and response format?
the endpoint is `https://nixos-search-5886075189.us-east-1.bonsaisearch.net/latest-19-20.09/_search`?
